In [12]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [8]:
X,y = load_diabetes(return_X_y=True)

In [15]:
X.shape

(442, 10)

In [16]:
y.shape

(442,)

In [10]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [13]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [14]:
lr.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [17]:
lr.intercept_

151.88334520854633

In [86]:
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.4399387660024644

In [21]:
X_train.shape

(353, 10)

In [77]:
class GDRegression:
    def __init__(self,learning_rate=0.01,epochs = 100):
        self.coef_ = None
        self.intercept_  = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        self.intercept_ = 0
        self.coef_= np.ones(X_train.shape[1])
        for i in range(self.epochs):
            #update all the intercept and coefficient
            y_pred = self.intercept_ + np.dot(X_train,self.coef_)
            intercept_dev = -2 * np.mean(y_train - y_pred)
            self.intercept_ = self.intercept_ -(self.lr *intercept_dev)
            
            coef_der = -2 * np.dot((y_train - y_pred),X_train)/X_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)
        print(self.intercept_,self.coef_)
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [88]:
gdr = GDRegression(learning_rate = 0.5,epochs = 1000)

In [89]:
gdr.fit(X_train,y_train)

152.0135263267291 [  14.38915082 -173.72674118  491.54504015  323.91983579  -39.32680194
 -116.01099114 -194.04229501  103.38216641  451.63385893   97.57119174]


In [80]:
lr.coef_,lr.intercept_

(array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
        -895.54360867,  561.21453306,  153.88478595,  126.73431596,
         861.12139955,   52.41982836]),
 151.88334520854633)

In [81]:
r2_score(y_test,y_pred)

0.4399387660024644

In [90]:
y_pred__ = gdr.predict(X_test)

In [91]:
r2_score(y_test,y_pred__)

0.4534524671450598