In [2]:
import numpy as np

In [10]:
a=np.ones((5,5))

In [11]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((5,4)).strides

(32, 8)

Code to check whether an array contains only integers or floating points

In [17]:
ints = np.ones(10,dtype=np.int32)
floats = np.ones(10,dtype = np.float64)
#Now checking the hierarchy
np.issubdtype(ints.dtype,np.integer)

True

In [18]:
np.issubdtype(floats.dtype,np.floating)

True

Reshaping Arrays

In [19]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [21]:
(arr.reshape(4,2)).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
'''The numpy module of Python provides a function called numpy. ravel, 
which is used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array.The flatten method behaves like ravel except it always returns a copy of
the data:'''

In [22]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

Concatenation of Arrays

In [24]:
arr1 = ([1,2,3] ,[4,5,6])
arr2 = ([7,8,9] ,[10,11,12])
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Repeating Elements

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
arr.repeat(2)
#each element gets repeated 2 times

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])