In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X,y=load_diabetes(return_X_y=True)

In [6]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [12]:
X_train,X_test

(array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
         -0.06291295,  0.04034337],
        [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
          0.01703713, -0.0052198 ],
        [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
         -0.09643322, -0.01764613],
        ...,
        [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
          0.08449528, -0.01764613],
        [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
          0.03605579, -0.04249877],
        [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
          0.06898221,  0.12732762]]),
 array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564384,  0.0493413 ,
          0.03125356,  0.07072993, -0.03949338, -0.00060925,  0.01963284],
        [-0.07816532,  0.05068012,  0.07786339,  0.05285819,  0.07823631,
          0.0644473 ,  0.02655027, -0.00259226,  0.04067226, -0.00936191],
        [ 0.04170844,  0.05068012, -0.01482845, -0.01714685, -0.00569682,
 

In [14]:
y_train,y_test

(array([ 48., 276.,  47., 175.,  60.,  81., 242., 197., 137., 129., 138.,
        160., 116., 101., 147., 100., 144.,  69., 219., 107., 168., 236.,
        109., 321., 128.,  43.,  72.,  55., 141., 283.,  59., 150., 346.,
        124., 186., 308., 272., 190.,  63.,  91.,  72.,  65., 158.,  90.,
        185.,  45., 199., 206.,  61., 139., 296., 281., 122.,  95.,  40.,
        127., 145., 108., 185.,  53., 132., 101., 263.,  94., 295., 259.,
        232., 124.,  77., 102.,  96.,  83., 263.,  71., 246.,  66., 115.,
        222.,  93., 129., 128., 163.,  99.,  92., 179., 140.,  94.,  97.,
        174.,  61., 202., 135.,  88., 152.,  69.,  31., 248., 275.,  64.,
         94.,  99., 109.,  90.,  37., 164., 274., 200.,  49., 214.,  85.,
        154., 134., 164., 189.,  64., 150., 245.,  67., 265., 151.,  75.,
        208., 292.,  90.,  59.,  44., 277.,  67.,  72., 182., 135., 275.,
         95., 332., 214.,  53., 141., 102.,  88.,  74., 103., 292.,  70.,
        138., 139.,  98.,  72.,  25., 

In [8]:
from sklearn.linear_model import Ridge

In [9]:
rg=Ridge(alpha=0.1,solver = 'cholesky')

In [15]:
rg.fit(X_train,y_train)

Ridge(alpha=0.1, solver='cholesky')

In [16]:
rg.coef_

array([   6.64275308, -172.24216584,  485.52387163,  314.68212174,
        -72.93932312,  -80.59005344, -174.46651489,   83.61665316,
        484.36328537,   73.58415414])

In [17]:
rg.intercept_

151.92548050708137

In [18]:
from sklearn.metrics import r2_score

In [19]:
y_pred=rg.predict(X_test)

In [20]:
r2_score(y_test,y_pred)

0.4519973816947851