In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [3]:
X,y=load_diabetes(return_X_y=True)

In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [9]:
from sklearn.linear_model import SGDRegressor

In [10]:
sgd = SGDRegressor(penalty = 'l2',max_iter = 500,eta0 = 0.1,learning_rate='constant',alpha=0.001)

In [11]:
'''eta0 is the learning rate '''

'eta0 is the learning rate '

In [12]:
sgd.fit(X_train,y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [13]:
sgd.intercept_

array([134.28865389])

In [14]:
sgd.coef_

array([  39.96126032, -100.52719106,  371.55226322,  252.09674868,
         -5.16209933,  -57.23743974, -168.64281504,  110.66780589,
        336.97455442,  106.01642757])

In [15]:
from sklearn.metrics import r2_score

In [16]:
y_pred = sgd.predict(X_test)
r2_score(y_test,y_pred)

0.38113913537365707

In [19]:
from sklearn.linear_model import Ridge

In [25]:
rd = Ridge(alpha = 0.001,solver = 'sparse_cg',max_iter= 500)

In [22]:
'''sparse-cg is uses gradient descent in the backend'''

'sparse-cg is uses gradient descent in the backend'

In [26]:
rd.fit(X_train,y_train)

Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [29]:
rd.coef_

array([  -8.76358146, -204.3211236 ,  518.37173084,  339.97538658,
       -787.69076389,  475.27472039,  106.78653802,  114.63206565,
        819.73954483,   52.87210202])

In [30]:
rd.intercept_

151.8853732866117

In [31]:
y_pred = rd.predict(X_test)

In [32]:
r2_score(y_test,y_pred)

0.4408664174481711

In [33]:
"""Thus the r2 Score increases significantly """

'Thus the r2 Score increases significantly '